sudo: required
language: python
python:
  - "3.6.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - wget https://bootstrap.pypa.io/get-pip.py
install:
  - python -V
  - pip -V
  - pip install nose
  - pip install -r requirements.txt
script:
  - make test
